name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        base_href: /fun-banking/
        github_access_token: ${{ secrets.PAGES_TOKEN }}
        build_configuration: production
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/fun-banking/browser

permissions:
  contents: write
